---
kind: Service
apiVersion: v1
metadata:
  name: heketi
  labels:
    glusterfs: heketi-service
    heketi: service
    k8s-app: storage-provisioner-gluster
    kubernetes.io/minikube-addons: storage-provisioner-gluster
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
    description: Exposes Heketi Service
spec:
  selector:
    glusterfs: heketi-pod
  ports:
  - name: heketi
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-topology
  labels:
    k8s-app: storage-provisioner-gluster
    kubernetes.io/minikube-addons: storage-provisioner-gluster
    addonmanager.kubernetes.io/mode: Reconcile
type: Opaque
data:
  minikube.json: ewogICJjbHVzdGVycyI6IFsKICAgIHsKICAgICAgIm5vZGVzIjogWwogICAgICAgIHsKICAgICAgICAgICJub2RlIjogewogICAgICAgICAgICAiaG9zdG5hbWVzIjogewogICAgICAgICAgICAgICJtYW5hZ2UiOiBbCiAgICAgICAgICAgICAgICAibWluaWt1YmUiCiAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAic3RvcmFnZSI6IFsKICAgICAgICAgICAgICAgICIxNzIuMTcuMC4xIgogICAgICAgICAgICAgIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgInpvbmUiOiAxCiAgICAgICAgICB9LAogICAgICAgICAgImRldmljZXMiOiBbCiAgICAgICAgICAgICIvZGV2L2Zha2UiCiAgICAgICAgICBdCiAgICAgICAgfQogICAgICBdCiAgICB9CiAgXQp9Cg==
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: heketi
  labels:
    glusterfs: heketi-deployment
    heketi: deployment
    k8s-app: storage-provisioner-gluster
    kubernetes.io/minikube-addons: storage-provisioner-gluster
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
    description: Defines how to deploy Heketi
spec:
  replicas: 1
  template:
    metadata:
      name: heketi
      labels:
        glusterfs: heketi-pod
        heketi: pod
        k8s-app: storage-provisioner-gluster
    spec:
      serviceAccountName: heketi-service-account
      containers:
      - image: quay.io/nixpanic/minukube-heketi:minikube
        imagePullPolicy: IfNotPresent
        name: heketi
        env:
        - name: HEKETI_USER_KEY
          value: "minikube"
        - name: HEKETI_ADMIN_KEY
          value: "minikube"
        - name: HEKETI_EXECUTOR
          value: "ssh"
        - name: HEKETI_SSH_KEYFILE
          value: "/etc/heketi/ssh/ssh-for-minikube"
        - name: HEKETI_SSH_USER
          value: "root"
        - name: HEKETI_SSH_PORT
          value: "2222"
        - name: HEKETI_FSTAB
          value: "/var/lib/heketi/fstab"
        - name: HEKETI_SNAPSHOT_LIMIT
          value: '14'
        - name: HEKETI_KUBE_GLUSTER_DAEMONSET
          value: "y"
        - name: HEKETI_IGNORE_STALE_OPERATIONS
          value: "true"
        - name: HEKETI_GLUSTERAPP_LOGLEVEL
          value: "debug"
        # initial topology.json in case the db does not exist
        - name: HEKETI_TOPOLOGY_FILE
          value: "/etc/heketi/topology/minikube.json"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: db
          mountPath: "/var/lib/heketi"
        - name: initial-topology
          mountPath: "/etc/heketi/topology"
        # only private ssh-key is needed, all other options are passed through
        # environment variables
        - name: ssh-key
          mountPath: /etc/heketi/ssh
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/hello"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/hello"
            port: 8080
      volumes:
      - name: db
        hostPath:
          path: "/var/lib/heketi"
      - name: initial-topology
        secret:
          secretName: heketi-topology
      - name: ssh-key
        secret:
          secretName: gluster-ssh-key
