---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: glusterfile
  labels:
    k8s-app: storage-provisioner-gluster
    kubernetes.io/minikube-addons: storage-provisioner-gluster
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: kubernetes.io/glusterfs
parameters:
    resturl: "http://heketi.default.svc.cluster.local:8080"
    restuser: "admin"
    restuserkey: "minikube"
    volumetype: "none"
